- name: Copy calico.yaml manifests
  template:
    src: calico.yaml
    dest: /tmp/calico.yaml
    force: yes

- name: Set Calico container image value
  replace:
    path: /tmp/calico.yaml
    regexp: "image: calico"
    replace: "image: {{ container_registry }}"

- name: Create Calico Deployment
  shell: kubectl apply -f /tmp/calico.yaml
